# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

evogenex_fit <- function(dat, nterm, nrep, nreg, nbranch, beta, epochs, bt, alpha, gamma) {
    .Call(`_EvoGeneX_evogenex_fit`, dat, nterm, nrep, nreg, nbranch, beta, epochs, bt, alpha, gamma)
}

