library(EvoGeneX)

data = read.csv('../data/short.csv', row.names=1, stringsAsFactors=F)
#print(data)

evog <- EvoGeneXfast()
evog$setTree('../data/short.newick')
evog$setRegimes('../data/short_reg.csv')
print("######## Fast Method ##############")
res = evog$fit(data, alpha=0.1, gamma.sq=0.01)
print(res)
print("######## Slow Method ##############")
#sink("slow.log", type=c("output"))
res = evog$fitSlow(data, alpha=0.1, gamma.sq=0.01)
print(res)
quit()

brown <- Brown()
brown$setTree('../data/drosophila9.newick')
res = brown$fit(data, gamma.sq=0.01)
print(res)
