# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

brown_fit <- function(nterm, nrep, dat, bt, gamma) {
    .Call(`_EvoGeneX_brown_fit`, nterm, nrep, dat, bt, gamma)
}

evogenex_fit <- function(nterm, nrep, nreg, dat, nbranch, beta, epochs, bt, alpha, gamma) {
    .Call(`_EvoGeneX_evogenex_fit`, nterm, nrep, nreg, dat, nbranch, beta, epochs, bt, alpha, gamma)
}

